version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "terragon-security-team"
    assignees:
      - "terragon-security-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    
    # Advanced grouping for intelligent dependency management
    groups:
      core-runtime:
        patterns:
          - "numpy*"
          - "pandas*"
          - "pyserial*"
          - "pydantic*"
          - "asyncio-mqtt*"
        update-types:
          - "minor"
          - "patch"
      
      testing-framework:
        patterns:
          - "pytest*"
          - "coverage*"
          - "factory-boy*"
          - "faker*"
          - "pytest-asyncio*"
          - "pytest-cov*"
          - "pytest-mock*"
          - "pytest-timeout*"
      
      security-dependencies:
        patterns:
          - "cryptography*"
          - "pycryptodome*"
          - "pyopenssl*"
          - "requests*"
          - "urllib3*"
          - "httpx*"
        # Security updates get highest priority
        dependency-type: "production"
      
      development-tools:
        patterns:
          - "black*"
          - "flake8*"
          - "mypy*"
          - "ruff*"
          - "pre-commit*"
        dependency-type: "development"
      
      hardware-drivers:
        patterns:
          - "pyftdi*"
          - "adafruit-*"
          - "RPi.GPIO*"
        update-types:
          - "patch"  # Hardware drivers need careful testing
      
      ai-ml-stack:
        patterns:
          - "torch*"
          - "transformers*"
          - "onnx*"
          - "tensorrt*"
        # AI/ML updates require extensive validation
        update-types:
          - "patch"
      
      sbom-security-tools:
        patterns:
          - "cyclonedx-*"
          - "pip-audit*"
          - "safety*"
          - "bandit*"
    
    # Ignore specific updates that require manual testing
    ignore:
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "plotly"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "terragon-devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "infrastructure"

  # Docker dependencies (if Dockerfile is added)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "terragon-devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"