# Prometheus configuration for Tiny LLM Edge Profiler monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tiny-llm-profiler'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Tiny LLM Profiler application metrics
  - job_name: 'tiny-llm-profiler'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['tiny-llm-profiler:8081']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'profiler_.*'
        target_label: component
        replacement: 'profiler'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_.*'
        target_label: component
        replacement: 'system'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__name__]
        regex: 'container_.*'
        target_label: component
        replacement: 'container'

  # Application-specific metrics discovery
  - job_name: 'profiler-tasks'
    scrape_interval: 5s
    metrics_path: /metrics/tasks
    static_configs:
      - targets: ['tiny-llm-profiler:8081']
    metric_relabel_configs:
      - source_labels: [task_type]
        target_label: profiling_task_type
      - source_labels: [platform]
        target_label: target_platform

  # Device health monitoring
  - job_name: 'device-health'
    scrape_interval: 30s
    metrics_path: /metrics/devices
    static_configs:
      - targets: ['tiny-llm-profiler:8081']
    metric_relabel_configs:
      - source_labels: [device_path]
        target_label: device
      - source_labels: [platform]
        target_label: device_platform

# Remote write configuration (optional, for long-term storage)
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    basic_auth:
      username: "${REMOTE_WRITE_USERNAME}"
      password: "${REMOTE_WRITE_PASSWORD}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500